CREATE TABLE IF NOT EXISTS migration(
	migration_id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE,
	ran_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS note(
	note_id INTEGER PRIMARY KEY AUTOINCREMENT,
	key VARCHAR(4095) NOT NULL UNIQUE,
	encrypted BOOLEAN NOT NULL DEFAULT FALSE,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS note_updated_at
	AFTER UPDATE
	ON note
BEGIN
	UPDATE note
	SET updated_at = CURRENT_TIMESTAMP
	WHERE note_id == NEW.note_id;
END;

CREATE TABLE IF NOT EXISTS tag(
	tag_id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS collection(
	collection_id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE
);
